{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentLabel }}
    spec:
      containers:
        - name: {{ .Values.deploymentLabel }}
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            {{- if .Values.profile_enabled }}
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: {{ .Values.global.configMapName }}
            {{- end -}}
            {{- if .Values.zipkin_enabled }}
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMapName }}
                  key: SPRING_ZIPKIN_BASEURL
            {{- end -}}
            {{- if .Values.oauth2_enabled}}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
                  name: {{ .Values.global.configMapName }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
                  name: {{ .Values.global.configMapName }}
            {{- end -}}
            {{- if .Values.mysql_enabled}}
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_DRIVER-CLASS-NAME
                  name: {{ .Values.global.configMapName }}
            - name: SPRING_DATA_SOURCE_URL
              value: {{ .Values.databaseUrl }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_USERNAME
                  name: {{ .Values.global.secretName }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_PASSWORD
                  name: {{ .Values.global.secretName }}
            - name: SPRING_DATASOURCE_HIKARI_AUTO-COMMIT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_HIKARI_AUTO-COMMIT
                  name: {{ .Values.global.configMapName }}
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
              valueFrom:
                configMapKeyRef:
                  key:   SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
                  name: {{ .Values.global.configmapName }}
            {{- end -}}
{{- end -}}