{{- define "common.secret" -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.global.secretName}}
data:
  SPRING_DATA_USER: {{ .Values.global.databaseUser }}
  SPRING_DATA_PASSWORD: {{ .Values.global.databasePassword }}
{{- end -}}