global:
  scrape_interval: 5s # Scrape Interval
  evaluation_interval: 1m # Evaluate rules interval
scrape_configs:
  - job_name: 'products'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']